name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checking out the latest code
        uses: actions/checkout@v3

      - name: Setting up nodejs for building codebase and Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]

      - name: Installing Dependencies
        run: pnpm install --frozen-lockfile

      - name: 'Create env file'
        run: |
          touch .env
          echo VITE_GOOGLE_MAP_API_KEY=${{ secrets.VITE_GOOGLE_MAP_API_KEY }} >> .env

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Add .nojekyll file
        run: touch ./static/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
